version: "3.8"

services:

  api:
    build:
      context: .
      dockerfile: Pedidos.Api/Dockerfile
    ports:
      - "5000:8080"
      - "5001:443"
    depends_on:
      - sqlserver
      - mongo
      - redis
      - rabbitmq
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__SqlServer=Server=sqlserver;Database=PedidosDb;User=sa;Password=Your_password123;
      - ConnectionStrings__MongoDb=mongodb://mongo:27017
      - ConnectionStrings__Redis=redis:6379
      - RabbitMq__Hostname=rabbitmq
      - RabbitMq__Username=guest
      - RabbitMq__Password=guest

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   # Porta para comunicação AMQP
      - "15672:15672" # Painel de administração (web UI)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - rabbit_data:/var/lib/rabbitmq

volumes:
  sql_data:
  mongo_data:
  redis_data:
  rabbit_data:
